dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: l00x2JXUS1BZjcYPpgmtRhM++jEYXLMnL/DjvOdy7w9Xsoz1hsYpMSOu397ZLNeM/gPkRZuqhO2XoXaMPrdTDkcH0HKNcxH226yCViviYOG881EYDxBueXlscm8Fx6Xk2FkUl9tr9OdGfCduCjTAKRg8ArD9JlR6gJL/p7qUicSPFGGyMSw2PGecXOdWxxJbTBbtzVW5+IOIHslem8mO+do6vVkwzdTsRH8uATTw30H4gVE31mGGEwaLIWBswD6f553p3J44vFsge32ZBxjLiXkO8Ss+nHoJdOG5CcfkEa2t2feeWXt31i/0eY7MjBOgUeFXAORI/PNNMEwVHCsTN8Isx6VfDCACqIGd7hWk5Qtj1X7gUOtEZxmIREPIOFxKrTNJhJUTixzwV6UDt8u1UCsMdIJCayAVOCTbiExVk/X8vWqRtmsc0464uwWWKmtfMQqKvMGX+1dccHydIxgLuKOA+835oamUZ1pbwrWV+8cmXdqRnLnsyozqhZoAcUSzxBwP635+L1L352HiSrjobtPbgMbgInAonSZmB0xojaCYVkz8s+1u73ERIAzZyBDyF208sUzOgLTaqfAFdeXGGc7VGuC4lBelE9rxtwMoXQF37A3ogKyFPnd2NTehE7vXu1WzaWH95kErk45AO7oRD+nrNaEu+UK17pcYF+voaRw=
