version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
          - back_net

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
          - back_net

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    networks:
          - back_net
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
          - back_net

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
